web:
  build: .
  #command: bin/rails server --port 3000 --binding 0.0.0.0
  #command: rails s
  command: bundle exec rails s -p 3000 -b '0.0.0.0'

  volumes:
    - .:/app

  environment:
    RAILS_ENV: development
  ports:
    - "3000:3000"
  links:
    - db

db:
  image: postgres:9.4.1
  ports:
    - "5432:5432"

